spring:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    schema: classpath:schema-h2.sql
    data: classpath:data-h2.sql