--Authors
INSERT INTO AUTHORS (id, username, name) values (1, 'wise_turtle','La Tortuga Sabia');
INSERT INTO AUTHORS (id, username, name) values (2, 'adolf_69','Adolf Hitler');
INSERT INTO AUTHORS (id, username, name) values (3, 'matusalen','Matusalén');
INSERT INTO AUTHORS (id, username, name) values (4, 'john_lenon','Juan Lima');
INSERT INTO AUTHORS (id, username, name) values (5, 'albert_einstein','Albert Einstein');
INSERT INTO AUTHORS (id, username, name) values (6, 'tu_madre','Tu madre');
INSERT INTO AUTHORS (id, username, name) values (7, 'dexter','Dexter');
INSERT INTO AUTHORS (id, username, name) values (8, 'paulo_cornelio','Paulo Cornélio');
INSERT INTO AUTHORS (id, username, name) values (9, 'paulo_coelho','Paulo Coelho');
INSERT INTO AUTHORS (id, username, name) values (10, 'buda','Buda');
INSERT INTO AUTHORS (id, username, name) values (11, 'mahatma_gandhi','Mahatma Gandhi');
INSERT INTO AUTHORS (id, username, name) values (12, 'mao_zedong','Mao Zedong');
INSERT INTO AUTHORS (id, username, name) values (13, 'el_yonqui_vanidoso','El Yonqui Vanidoso');
INSERT INTO AUTHORS (id, username, name) values (14, 'paqui','Paqui');
INSERT INTO AUTHORS (id, username, name) values (15, 'el_rey_arturo','El Rey Arturo');
INSERT INTO AUTHORS (id, username, name) values (16, 'juan_car','Juan Carlos I, Rey de España\u002E');
INSERT INTO AUTHORS (id, username, name) values (17, 'pío_xii','Pío XII');
INSERT INTO AUTHORS (id, username, name) values (18, 'dr_gregory_house','Dr\u002E Gregory House');
INSERT INTO AUTHORS (id, username, name) values (19, 'el_rabino','El Rabino Salom\u00F3n');
INSERT INTO AUTHORS (id, username, name) values (20, 'hodor','Hodor');
INSERT INTO AUTHORS (id, username, name) values (21, 'mi_madre','Mi madre');
INSERT INTO AUTHORS (id, username, name) values (22, 'inygo_montoya','Iñigo Montoya');
INSERT INTO AUTHORS (id, username, name) values (23, 'ramona','Ramona, el día de su divorcio');
INSERT INTO AUTHORS (id, username, name) values (24, 'confucio','Confucio');
--Advices
INSERT INTO ADVICES (USERID, sentence) values (1, 'Si mi primer consejo quieres, pagar la cuota debes');
INSERT INTO ADVICES (USERID, sentence) values (2, 'Observa el horizonte pequeño aprendiz... no dejes de mirar al horizonte mientras te hago un hijo');
INSERT INTO ADVICES (USERID, sentence) values (3, 'A falta de pan, buenas son tortas. En tu cara.');
INSERT INTO ADVICES (USERID, sentence) values (4, 'Hay muchas cosas en el mundo que no sabes, prueba a plantar un arbol en el ano de Rajoy, muchas cosas buenas ocurrir\u00E1n pues el sol se pone después de cada retardecer\u002E');
INSERT INTO ADVICES (USERID, sentence) values (5, 'Hay muchas cosas en el mundo que no sabes, prueba a plantar un arbol en el ano de Rajoy, muchas cosas buenas ocurrir\u00E1n pues el sol se pone después de cada retardecer\u002E');
INSERT INTO ADVICES (USERID, sentence) values (6, 'Elige las fresas como si de tu avuela se tratase, no te digo que ser\u00E1 f\u00E1cil te digo que no te debo pasta, cuidado con la luna llena pues en la vida hay cosas m\u00E1s importantes que trabajar\u002E');
INSERT INTO ADVICES (USERID, sentence) values (7, '¿Un consejo?, yo que se ti@, no te rayes y sal a tomar unas chupitos de mandarina\u002E');
INSERT INTO ADVICES (USERID, sentence) values (8, '¿Un consejo?, yo que se ti@, no te rayes y sal a tomar unas chupitos de mandarina\u002E');
INSERT INTO ADVICES (USERID, sentence) values (9, 'A mi me gustan los penes como las mandarinas: naranjas, bien puedes ir por la selva a las 12 de la noche sin protecci\u00F3n porque total, vas a morir igual\u002E');
INSERT INTO ADVICES (USERID, sentence) values (10,'Si eres infiel a tu pareja no pasa nada, plantante delante suyo con mucha autoridad y di: Cariño, te he puesto los cuernos por lo menos con 12 personas\u002E\u002E\u002E pero ninguna me dan tan buen sexo como tu\u002E');
INSERT INTO ADVICES (USERID, sentence) values (11,'Si la vida te calabazas, hazte un zumo, pero ya te digo yo que el zumo de calabazas es un puta mierda\u002E');
INSERT INTO ADVICES (USERID, sentence) values (12,'Algunos dicen que la felicidad esta en la sonrisa de un niño, otros que est\u00E1 en la satisfacci\u00F3n del trabajo bien hecho, pero los m\u00E1s sabios saben que la felicidad esta en la pizza\u002E');
INSERT INTO ADVICES (USERID, sentence) values (13,'No te digo que ser\u00E1 f\u00E1cil, te digo que valdr\u00E1 la pena\u002E Al igual que una serpiente repta durante un kilometro para morir aplastada bajo las ruedas de un altom\u00F3vil, tu triunfar\u00E1s en la vida');
INSERT INTO ADVICES (USERID, sentence) values (14,'Las historias est\u00E1n bien si te las cuenta tu abuela jubilado, pero tu dejate de historias y ponte a trabajar, ¡vago de mierda!');
INSERT INTO ADVICES (USERID, sentence) values (15,'El mundo animal ha sufrido durante mucho tiempo el yugo opresor de la raza humana, ya va siendo hora de que nos esclavicen y nos metan en granjas de producci\u00F3n en espacios muy reducidos, donde succionen nuestros fluidos corporales mientras nos ceban a piensos cargados de hormonas\u002E Sería una justicia muy poética el porvenir\u002E');
INSERT INTO ADVICES (USERID, sentence) values (16,'¡Eh, devuelvame mi paraguas joven gmaberro!');
INSERT INTO ADVICES (USERID, sentence) values (17,'Imagine there''s no heaven\u002E It''s easy if you try\u002E No hell below us\u002E Above us only sky\u002E Imagine all the people\u002E Living for todaaaaaaaaaaaay\u002E\u002E\u002E AHAAAAAAAAAAAAA-AAAAAHHHHHHHHHHHHHHHH\u002E\u002E\u002E');
INSERT INTO ADVICES (USERID, sentence) values (18,'Dejad de poner frases en internet y decir que las he escrito yo\u002E');
INSERT INTO ADVICES (USERID, sentence) values (19,'Y los niños? Es que nadie piensa en los niños?!');
INSERT INTO ADVICES (USERID, sentence) values (20,'¡No hombre no!, Esos cad\u00E1veres no son de su familia, yo no soy un asesino\u002E Con su permiso, me voy retirando con viento fresco\u002E Besis');
INSERT INTO ADVICES (USERID, sentence) values (21,'Qué es la vida, sino un breve lapsus en el tiempo, tremendamente improbable y tremendamente efímero? No te sorprendas con grandes cosas y asombrate por las cosas pequeñas, pues mientras m\u00E1s vives, menos sentido tendr\u00E1 tu existencia (de mierda)');
INSERT INTO ADVICES (USERID, sentence) values (22,'Hay un oso invernal comiendo hojas de bambú que te va a matar pl\u00E1cidamente\u002E');
INSERT INTO ADVICES (USERID, sentence) values (23,'En casi todas las actividades de la vida y el placer se acaba uno manchando, y lo sabes');
INSERT INTO ADVICES (USERID, sentence) values (24,'Se me ha acabado el papel del culo');
INSERT INTO ADVICES (USERID, sentence) values (1, 'Si deseas algo con todas tus fuerzas, el universo conspira para que lo consigas\u002E Bueno, no siempre, pero a veces sí\u002E Aunque la mayoría de las veces no\u002E No sé, me voy a masturbar y luego lo medito\u002E');
INSERT INTO ADVICES (USERID, sentence) values (2, 'Si pagas con cacahuetes, tendr\u00E1s monos que escribir\u00E1n libros por ti\u002E');
INSERT INTO ADVICES (USERID, sentence) values (3, 'Yo tengo un moco, lo miro con deseo\u002E');
INSERT INTO ADVICES (USERID, sentence) values (4, 'Siento que est\u00E1s bien, siento que est\u00E1s agusto, siento tu cuerpo, siento tu mente, siento cincuenta, siticientos veinte\u002E');
INSERT INTO ADVICES (USERID, sentence) values (5, 'Vendo Opel Corsa\u002E');
INSERT INTO ADVICES (USERID, sentence) values (6, 'Digan lo que digan, los pelos del culo abrigan\u002E');
INSERT INTO ADVICES (USERID, sentence) values (7, 'Ke os flipais muxo los unibersitarios ai con vuestros estudios pero luego te meto un navajazo y no ai titulo ke te salve jajajajjj');
INSERT INTO ADVICES (USERID, sentence) values (8, 'Todos los problemas de la vida sirven para enerñarnos algo, inclusive aquellos que no solucionamos\u002E Salvo los errores aleatorios de Eclipse, esos no valen para una puta mierda\u002E');
INSERT INTO ADVICES (USERID, sentence) values (9, 'Gallina vieja hace buen caldo');
INSERT INTO ADVICES (USERID, sentence) values (10,'Siempre sé tú mismo\u002E Pero si puedes ser Batman, mejor sé Batman, que cualquier cosa es ser mejor que tú\u002E');
INSERT INTO ADVICES (USERID, sentence) values (11,'La droga est\u00E1 conceptuada, socialmente, muy mal\u002E Pero la droga es\u002E\u002E\u002E pues\u002E\u002E\u002E ¿Qué te voy a decir yo?\u002E\u002E\u002E Es la auténtica salud\u002E\u002E\u002E El bienestar\u002E\u002E\u002E La alegría\u002E');
INSERT INTO ADVICES (USERID, sentence) values (12,'Cuando los días resultan iguales es porque el hombre ha dejado de percibir las cosas buenas vendo Opel Corsa en buen estado duerme en garaje que surgen de su vida cada vez que el sol cruza el cielo');
INSERT INTO ADVICES (USERID, sentence) values (13,'Meterte en una hipoteca a 40 años es como decidir un caluroso día de verano que vas a pasar el resto de tu vida en manga corta\u002E');
INSERT INTO ADVICES (USERID, sentence) values (14,'Si los tontos volasen, a ti te iban a dar de comer en helic\u00F3ptero\u002E');
INSERT INTO ADVICES (USERID, sentence) values (15,'Antes la muerte que perder la vida\u002E');
INSERT INTO ADVICES (USERID, sentence) values (16,'NO trates con prioridad a quien te trate como una opci\u00F3n\u002E M\u00E1talo\u002E Solucionado\u002E');
INSERT INTO ADVICES (USERID, sentence) values (17,'Valora lo que tienes pues algún dia se ir\u00E1\u002E Pero bueno, si son hemorroides mejor que se vayan\u002E\u002E\u002E ¿no?');
INSERT INTO ADVICES (USERID, sentence) values (18,'hij@, te voy a decir dos palabras que te van a abrir muchas puertas en la vida\u002E\u002E\u002E Empujar y Tirar');
INSERT INTO ADVICES (USERID, sentence) values (19,'El honor es lo que usan los dislexicos para calentar pizzas\u002E');
INSERT INTO ADVICES (USERID, sentence) values (20,'En mi hambre mando yo\u002E');
INSERT INTO ADVICES (USERID, sentence) values (21,'Lo que comas, cagar\u00E1s\u002E');
INSERT INTO ADVICES (USERID, sentence) values (22,'Si te matas con un coche te has muerto, pero si te matas con una moto te matas de verdad\u002E');
INSERT INTO ADVICES (USERID, sentence) values (23,'Soy una persona corriente y normal\u002E\u002E\u002E pero joder! Entre tanto anormal parece que soy alguien\u002E');
INSERT INTO ADVICES (USERID, sentence) values (24,'Lo siento mucho, me he equivocado y no volver\u00E1 a ocurrir\u002E');
INSERT INTO ADVICES (USERID, sentence) values (1, 'My body is ready for you, baby\u002E');
INSERT INTO ADVICES (USERID, sentence) values (2, 'Quien caga duro y mea fuerte \u002E\u002E\u002E no tiene miedo a la muerte\u002E');
INSERT INTO ADVICES (USERID, sentence) values (3, 'Teneis permiso para hacer lo que quer\u00E1is, eso sí, que no os vean\u002E');
INSERT INTO ADVICES (USERID, sentence) values (4, 'Si quiere cambiar su vida haga algo, no crea en sus propias justificaciones; no se enclaustre y finja que es usted feliz');
INSERT INTO ADVICES (USERID, sentence) values (5, 'Cuando termina el juego,el rey y el pe\u00F3n vuelven a la misma caja\u002E');
INSERT INTO ADVICES (USERID, sentence) values (6, 'Uno se hace mayor cuando deja de tener curiosidad por las cosas\u002E');
INSERT INTO ADVICES (USERID, sentence) values (7, 'Gasté parte de mi fortuna en fiestas, drogas y alcohol, el resto lo malgasté');
INSERT INTO ADVICES (USERID, sentence) values (8, 'Vive tal y como piensas o acabar\u00E1s pensando tal y como vives\u002E O algo así\u002E');
INSERT INTO ADVICES (USERID, sentence) values (9, 'Aguanta el portoooooon! Aguanta el port\u00F3nador! HODOR! HODOR! HODOR!');
INSERT INTO ADVICES (USERID, sentence) values (10,'No hables a no ser que tus palabras sean mejores que el silencio\u002E A no ser que el silencio se vuelva inc\u00F3modo\u002E Si es así, di cualquier gilipollez\u002E');
INSERT INTO ADVICES (USERID, sentence) values (11,'No existe la m\u00E1s mínima prueba que apoye la idea de que la vida sea algo serio\u002E');
INSERT INTO ADVICES (USERID, sentence) values (12,'Una dieta equilibrada consiste en tener una galleta en cada mano\u002E');
INSERT INTO ADVICES (USERID, sentence) values (13,'Si tienes que escoger entre dos males, elige el que no hayas probado antes\u002E A ver si así dej\u00E1is de votar al PP');
INSERT INTO ADVICES (USERID, sentence) values (14,'Jam\u00E1s han matado a nadie mientras lavaba los platos\u002E');
INSERT INTO ADVICES (USERID, sentence) values (15,'Los hombres son de la tierra, Las mujeres son de la tierra\u002E Supéralo\u002E');
INSERT INTO ADVICES (USERID, sentence) values (16,'Para cada acci\u00F3n, hay un programa gubernamental contrario de igual fuerza\u002E');
INSERT INTO ADVICES (USERID, sentence) values (17,'Siempre hay un tonto m\u00E1s de lo que creías\u002E');
INSERT INTO ADVICES (USERID, sentence) values (18,'Hoy hace un bonito día\u002E\u002E\u002E\u002E ver\u00E1s c\u00F3mo viene alguien y te lo jode\u002E\u002E\u002E');
INSERT INTO ADVICES (USERID, sentence) values (19,'Llora, llora que menos meas');
INSERT INTO ADVICES (USERID, sentence) values (20,'Todas las opiniones son igual de validas\u002E\u002E\u002E menos la de los seres humanos\u002E');
INSERT INTO ADVICES (USERID, sentence) values (21,'Hola, me llamo Iñigo Montoya, tú mataste a mi padre\u002E Prep\u00E1rate a morir\u002E');
INSERT INTO ADVICES (USERID, sentence) values (22,'Si alguien te quita el marido, la mejor venganza es dejar que se lo quede\u002E\u002E\u002E jojojo');
INSERT INTO ADVICES (USERID, sentence) values (23,'Hostia! Que hambre me est\u00E1 entrando!');