DROP TABLE IF EXISTS ADVICES CASCADE;
DROP TABLE IF EXISTS AUTHORS CASCADE;

CREATE TABLE IF NOT EXISTS AUTHORS (
  ID SERIAL PRIMARY KEY NOT NULL,
  USERNAME VARCHAR NOT NULL,
  NAME VARCHAR
);

ALTER SEQUENCE AUTHORS_ID_SEQ MINVALUE 0 START WITH 1;
SELECT SETVAL('AUTHORS_ID_SEQ', 0);

CREATE TABLE IF NOT EXISTS ADVICES (
  ID SERIAL PRIMARY KEY NOT NULL,
  USERID integer REFERENCES AUTHORS(ID) NOT NULL,
  SENTENCE VARCHAR NOT NULL
);

ALTER SEQUENCE ADVICES_ID_SEQ MINVALUE 0 START WITH 1;
SELECT SETVAL('ADVICES_ID_SEQ', 0);