CREATE TABLE IF NOT EXISTS AUTHORS (
  ID SERIAL PRIMARY KEY NOT NULL,
  USERNAME VARCHAR NOT NULL,
  NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS ADVICES (
  ID SERIAL PRIMARY KEY NOT NULL,
  USERID integer REFERENCES AUTHORS(ID) NOT NULL,
  SENTENCE VARCHAR NOT NULL
);

