CREATE TABLE AUTHORS (
  ID INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR NOT NULL,
  NAME VARCHAR,
  PRIMARY KEY (ID)
);

CREATE TABLE ADVICES (
  ID INT NOT NULL AUTO_INCREMENT,
  USERID VARCHAR NOT NULL,
  SENTENCE VARCHAR,
  PRIMARY KEY (ID),
  FOREIGN KEY (USERID) REFERENCES AUTHORS(ID)
);

