version: "3.1"
services:

  sentences:
    container_name: sentences
    build: ./app
    env_file:
      - var.env
    restart: always
    ports:
      - "8081:8081"
    links:
      - database:db
    depends_on:
      - database

  database:
    container_name: database
    build: ./db
    env_file:
      - var.env
    restart: always
    ports:
      - "5432:5432"