node {
    def mvnHome
    stage('Preparation'){
        git 'https://github.com/scatt89/sentences.git'
        mvnHome = tool 'M3'
    }
    stage('Build'){
        if(isUnix()){
            sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
        }else{
            bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
        }
    }
    def originJar
    stage('Deploy'){
        //copia de la carpeta target el archivo sentences-*-SNAPSHOT.jar
        //sobreescribe el archivo copiado a la carpeta ci/conteiners/app con el nombre sentences.jar sobrescribiendo el actual
        if(isUnix()){
            sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
        }else{
            bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
        }
    }

}